"""Phase-4 target validation surfaces."""

from intent_pipeline.phase4.contracts import (
    CapabilityMatrix,
    FALLBACK_TIER_ORDER,
    MOCK_STAGE_ORDER,
    PHASE4_ENGINE_SCHEMA_VERSION,
    PHASE4_FALLBACK_SCHEMA_VERSION,
    PHASE4_MOCK_SCHEMA_VERSION,
    PHASE4_VALIDATION_SCHEMA_VERSION,
    FallbackAttempt,
    FallbackDecision,
    FallbackErrorCode,
    FallbackOutcome,
    FallbackTier,
    MockDecision,
    MockErrorCode,
    MockStage,
    MockStep,
    MockStepStatus,
    MockTrace,
    Phase4BoundaryErrorCode,
    Phase4BoundaryViolation,
    Phase4Result,
    PolicyContract,
    RequiredCapabilityBinding,
    RouteSpecTarget,
    RouteToolBinding,
    ToolCapability,
    ValidationContractError,
    ValidationDecision,
    ValidationErrorCode,
    ValidationIssue,
    ValidationReport,
    ValidationSeverity,
    parse_capability_matrix,
    parse_policy_contract,
    parse_route_spec_target,
)
from intent_pipeline.phase4.engine import run_phase4
from intent_pipeline.phase4.fallback import resolve_fallback
from intent_pipeline.phase4.mock_executor import run_mock_execution
from intent_pipeline.phase4.validator import validate_target


__all__ = [
    "CapabilityMatrix",
    "FALLBACK_TIER_ORDER",
    "MOCK_STAGE_ORDER",
    "PHASE4_ENGINE_SCHEMA_VERSION",
    "PHASE4_FALLBACK_SCHEMA_VERSION",
    "PHASE4_MOCK_SCHEMA_VERSION",
    "PHASE4_VALIDATION_SCHEMA_VERSION",
    "FallbackAttempt",
    "FallbackDecision",
    "FallbackErrorCode",
    "FallbackOutcome",
    "FallbackTier",
    "MockDecision",
    "MockErrorCode",
    "MockStage",
    "MockStep",
    "MockStepStatus",
    "MockTrace",
    "Phase4BoundaryErrorCode",
    "Phase4BoundaryViolation",
    "Phase4Result",
    "PolicyContract",
    "RequiredCapabilityBinding",
    "RouteSpecTarget",
    "RouteToolBinding",
    "ToolCapability",
    "ValidationContractError",
    "ValidationDecision",
    "ValidationErrorCode",
    "ValidationIssue",
    "ValidationReport",
    "ValidationSeverity",
    "parse_capability_matrix",
    "parse_policy_contract",
    "parse_route_spec_target",
    "resolve_fallback",
    "run_phase4",
    "run_mock_execution",
    "validate_target",
]
