"""Phase-4 target validation surfaces."""

from intent_pipeline.phase4.contracts import (
    CapabilityMatrix,
    MOCK_STAGE_ORDER,
    PHASE4_MOCK_SCHEMA_VERSION,
    PHASE4_VALIDATION_SCHEMA_VERSION,
    MockDecision,
    MockErrorCode,
    MockStage,
    MockStep,
    MockStepStatus,
    MockTrace,
    PolicyContract,
    RequiredCapabilityBinding,
    RouteSpecTarget,
    RouteToolBinding,
    ToolCapability,
    ValidationContractError,
    ValidationDecision,
    ValidationErrorCode,
    ValidationIssue,
    ValidationReport,
    ValidationSeverity,
    parse_capability_matrix,
    parse_policy_contract,
    parse_route_spec_target,
)
from intent_pipeline.phase4.mock_executor import run_mock_execution
from intent_pipeline.phase4.validator import validate_target


__all__ = [
    "CapabilityMatrix",
    "MOCK_STAGE_ORDER",
    "PHASE4_MOCK_SCHEMA_VERSION",
    "PHASE4_VALIDATION_SCHEMA_VERSION",
    "MockDecision",
    "MockErrorCode",
    "MockStage",
    "MockStep",
    "MockStepStatus",
    "MockTrace",
    "PolicyContract",
    "RequiredCapabilityBinding",
    "RouteSpecTarget",
    "RouteToolBinding",
    "ToolCapability",
    "ValidationContractError",
    "ValidationDecision",
    "ValidationErrorCode",
    "ValidationIssue",
    "ValidationReport",
    "ValidationSeverity",
    "parse_capability_matrix",
    "parse_policy_contract",
    "parse_route_spec_target",
    "run_mock_execution",
    "validate_target",
]
